# 1. WAP to convert temperature from Celsius to Fahrenheit.

In [2]:
def cel_to_fah(celsius):
    fahrenheit = (celsius * 9/5) + 32
    return fahrenheit
def fah_to_cel(fahrenheit):
    celsius = (fahrenheit - 32) * 5/9
    return celsius


celcius = float(input("Enter temperature in Celsius: "))
fahrenheit = cel_to_fah(celcius)
print("Temperature in Fahrenheit:", fahrenheit)

fahrenheit = float(input("Enter temperature in Fahrenheit: "))
celsius = fah_to_cel(fahrenheit)
print("Temperature in Celsius:", celsius)

Enter temperature in Celsius: -40
Temperature in Fahrenheit: -40.0
Enter temperature in Fahrenheit: 32
Temperature in Celsius: 0.0

# 2. WAP to swap two numbers

In [3]:
def swap_numbers(a, b):
  a, b = b, a
  return a, b

a = 10
b = 20
a, b = swap_numbers(a, b)
print("a =", a)
print("b =", b)

a = 20
b = 10

# 3. WAP to check whether a given year is leap year or not

In [4]:
def leap_year(year):
  if (year % 4 == 0 and year % 100 != 0) or year % 400 == 0:
    return True
  else:
    return False

year = int(input("Enter a year: "))
if leap_year(year):
  print(year, "is a leap year.")
else:
  print(year, "is not a leap year.")

Enter a year: 2024
2024 is a leap year.

# 4. WAP to display reverse of a number

In [6]:
def reverse_number(num):
  reversed_num = 0
  while num > 0:
    digit = num % 10
    reversed_num = reversed_num * 10 + digit
    num //= 10
  return reversed_num

num = int(input("Enter a number: "))
print("Reversed number:", reverse_number(num))

Enter a number: 256
Reversed number: 652

# 5. WAP to find factors of a given number

In [8]:
def factors(num):
  print("Factors of", num, "are:")
  for i in range(1, num + 1):
    if num % i == 0:
      print(i)

num = int(input("Enter a number: "))
factors(num)

Enter a number: 24
Factors of 24 are:
1
2
3
4
6
8
12
24

# 6. WAP to generate prime number series up to n

In [9]:
def prime_series(start, end):
  print("Prime numbers between", start, "and", end, "are:")
  for num in range(start, end + 1):
    if num > 1:
      for i in range(2, num):
        if (num % i) == 0:
          break
      else:
        print(num)

start = int(input("Enter the starting number: "))
end = int(input("Enter the ending number: "))
prime_series(start, end)

Enter the starting number: 1
Enter the ending number: 50
Prime numbers between 1 and 50 are:
2
3
5
7
11
13
17
19
23
29
31
37
41
43
47

# 7. Write a program which makes use of function to display all such numbers which are divisible by 7 but are not a multiple of 5, between 1000 and 2000.

In [13]:
def divisible_by_7_not_multiple_of_5(start, end):
  print("Numbers divisible by 7 but not a multiple of 5 between", start, "and", end, "are:")
  for num in range(start, end + 1):
    if num % 7 == 0 and num % 5 != 0:
      print(num, end=", ")

start = 1000
end = 2000
divisible_by_7_not_multiple_of_5(start, end)

Numbers divisible by 7 but not a multiple of 5 between 1000 and 2000 are:
1001, 1008, 1022, 1029, 1036, 1043, 1057, 1064, 1071, 1078, 1092, 1099, 1106, 1113, 1127, 1134, 1141, 1148, 1162, 1169, 1176, 1183, 1197, 1204, 1211, 1218, 1232, 1239, 1246, 1253, 1267, 1274, 1281, 1288, 1302, 1309, 1316, 1323, 1337, 1344, 1351, 1358, 1372, 1379, 1386, 1393, 1407, 1414, 1421, 1428, 1442, 1449, 1456, 1463, 1477, 1484, 1491, 1498, 1512, 1519, 1526, 1533, 1547, 1554, 1561, 1568, 1582, 1589, 1596, 1603, 1617, 1624, 1631, 1638, 1652, 1659, 1666, 1673, 1687, 1694, 1701, 1708, 1722, 1729, 1736, 1743, 1757, 1764, 1771, 1778, 1792, 1799, 1806, 1813, 1827, 1834, 1841, 1848, 1862, 1869, 1876, 1883, 1897, 1904, 1911, 1918, 1932, 1939, 1946, 1953, 1967, 1974, 1981, 1988,

# 8. WAP to check whether a number is a palindrome or not

In [14]:
def palindrome(num):
  temp = num
  reversed_num = 0
  while temp > 0:
    digit = temp % 10
    reversed_num = reversed_num * 10 + digit
    temp //= 10
  if num == reversed_num:
    return True
  else:
    return False

num = int(input("Enter a number: "))
if palindrome(num):
  print(num, "is a palindrome.")
else:
  print(num, "is not a palindrome.")

Enter a number: 121
121 is a palindrome.

# 9. WAP to check whether
*   is a perfect number
*   is an Armstrong number

In [17]:
def perfect_number(num):
  sum = 0
  for i in range(1, num):
    if num % i == 0:
      sum += i
  if sum == num:
    return True
  else:
    return False

def armstrong_number(num):
  sum = 0
  temp = num
  while temp > 0:
    digit = temp % 10
    sum += digit ** 3
    temp //= 10
  if sum == num:
    return True
  else:
    return False

num = int(input("Enter a number: "))
if perfect_number(num):
  print(num, "is a perfect number.")
else:
  print(num, "is not a perfect number.")

if armstrong_number(num):
  print(num, "is an Armstrong number.")
else:
  print(num, "is not an Armstrong number.")

Enter a number: 496
496 is a perfect number.
496 is not an Armstrong number.

# 10. WAP to generate the Fibonacci series upto n.

In [19]:
def fibonacci(n):
  a = 0
  b = 1
  if n <= 0:
    print("Invalid input.")
  elif n == 1:
    print(a)
  else:
    print(a, end=" ")
    print(b, end=" ")
    for i in range(2, n):
      c = a + b
      print(c, end=" ")
      a = b
      b = c

n = int(input("Enter the number of terms: "))
fibonacci(n)

Enter the number of terms: 5
0 1 1 2 3